//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Dropper.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicaoValor
    {
        public int CodMedidorVazao { get; set; }
        public int CodMedicaoVazaoValor { get; set; }
        public System.DateTime DataMedicaoVazaoValor { get; set; }
        public double Valor { get; set; }
    
        public virtual MedidorVazao MedidorVazao { get; set; }
    }
}
