//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Dropper.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedidorVazao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedidorVazao()
        {
            this.MedicaoValors = new HashSet<MedicaoValor>();
        }
    
        public int CodMedidorVazao { get; set; }
        public int Identificacao { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicaoValor> MedicaoValors { get; set; }
    }
}
