//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Dropper.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENSOR
    {
        public int ID_SENSOR { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual VAZAO VAZAO { get; set; }
    }
}
