//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Dropper.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAZAO
    {
        public int ID_VAZAO { get; set; }
        public int ID_SENSOR { get; set; }
        public double VALOR { get; set; }
        public System.DateTime DT_MEDICAO { get; set; }
    
        public virtual SENSOR SENSOR { get; set; }
    }
}
